### ISSUE TITLE
Very hard to find files of the failed test after many passed tests

### ISSUE THREAD

**Issue by Gerold103** [tarantool/luatest#197]
Instance folders in `var/nnn_<suite>/` are kept for all the running and finished tests. As a result, if a test hangs and there were 10 tests who passed before, each created a couple of instances, then you have > 20 folders like `master_nnnn` and `replica_xxxx`. Good luck with finding which pair is from the test which is hanging. They need to be grouped by tests somehow.

**Comment by ochaplashkin** [comment]
We came to an understanding of the file structure after our discussion with @sergepetrenko:

```lua
-- gh-XXXX-test.lua
foo = cluster:new({})
foo:build_and_add_server(node1)
foo:build_and_add_server(node2)

bar = cluster:new({})
bar:build_and_add_server(node1)
bar:build_and_add_server(node2)

foo_s = server:new({}) -- single server instance without alias
bar_s = server:new({alias='tom'}) -- single server with alias
```

```
-- tarantool repo
/test
    /replication-luatest
        gh-XXXX-test.lua
             cluster "a":
                 node1 workdir:  /tmp/t/XXX_replication-luatest/gh-XXXX/rs_AAAA/node1-<UID>
                 node2 workdir:  /tmp/t/XXX_replication-luatest/gh-XXXX/rs_AAAA/node2-<UID>
             cluster "b":
                 node1 workdir:  /tmp/t/XXX_replication-luatest/gh-XXXX/rs_BBBB/node1-<UID>
                 node2 workdir:  /tmp/t/XXX_replication-luatest/gh-XXXX/rs_BBBB/node2-<UID>
```
```
-- tmp directory
/tmp
    /t
        /XXX_replication-luatest
             /gh-XXXX
                 /rs_AAAA
                     /node1-<UID>
                         ...
                     /node2-<UID>
                         ...
                 /rs_BBBB
                     /node1-<UID>
                         ...
                     /node2-<UID>
                         ...
                 /server-<UID>
                     ...
                 /tom-<UID>
                     ...
```
Details:

`XXX` - number of thread from test-run
`gh-XXXX` - part of test file name (e.g. gh-XXXX_test.lua)
`rs_AAAA` -  a subdirectory of some unique replica set for cluster **"a"**, `rs_<UID>`
`rs_BBBB` -  a subdirectory of some unique replica set for cluster **"b"**, `rs_<UID>`

**Comment by ochaplashkin** [comment]
@ylobankov Thank you for telling me about the nuance of file systems and socket files!

### Briefly from his story:

There is a variable `POSIX_MAX_PATH`, the value of which can vary from **92** to **108** (or up to **256**) depending on the operating system ([link](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/sys_un.h.html#tag_13_67_04)).

For example ([see this answer](https://unix.stackexchange.com/a/367012)):
- [OpenBSD](http://man.openbsd.org/unix.4): 104 characters;
- [FreeBSD](https://www.freebsd.org/cgi/man.cgi?query=unix&sektion=4): 104 characters;
- [Mac OS X 10.9](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man4/unix.4.html): 104 characters.

Thus, our path (e.g. `/tmp/t/XXX_replication-luatest/gh-XXXX/rs_AAAA/node1-<UID>` ) can be too long.

### His suggestion
Use the `symlink` concept so that the path to the socket file is short.


The directory tree project currently looks like an **associative array** (keys are the full path with a symlink to short paths to the server's working folders):
```
/tmp
    /t
       /keys (naming is just for a technical example, will be change)
            /XXX_replication-luatest
                 /gh-XXXX
                     /rs_AAAA
                         /node1-<UID> (symlink)
      /values (naming is just for a technical example, will be change)
          /node1-<UID>
          /server-<UID>
          /tom-<UID>
```
@sergepetrenko, these are the nuances of **technical** implementation. I think that the algorithm for finding the right files will not change and will be the same as we discussed it :slightly_smiling_face:

**Comment by sergepetrenko** [comment]
@ochaplashkin, sounds good to me, thanks!

**Comment by ochaplashkin** [comment]
Finally, we found a more **elegant** way to show the link between server artifacts and a test: `classic output`.

Example:
```lua
g.before_test('test_foo', function()
    g.s = Server:new()
    g.s:start()
end)

g.test_foo = function()
   t.assert_equals(1,2) -- Boom!
end

g.after_test('test_foo', function()
   g.s:drop()
end)
```

Output:
```
Failed tests:
-------------

1) foo.test_foo
...test/foo_test.lua:17: expected: 2, actual: 1
stack traceback:
	...
	[C]: in function 'xpcall'
artifacts:
#	server -> /tmp/t/artifacts/server-7BlPt1uxVfv6
```
Simple action:
```bash
$ ls /tmp/t/artifacts/server-7BlPt1uxVfv6
00000000000000000000.snap  00000000000000000000.xlog  00000000000000000000.xlog  server.log
```
