### ISSUE TITLE
Add `preloaded` hooks for before/after `each`, `all` and `suite`

### ISSUE THREAD

**Issue by ochaplashkin** [tarantool/luatest#380]
In the future, there may be `Lua` modules that want to add certain behaviour to `before_all / after_all` or `before_suite / after_suite`. This way, something can be done automatically without the developer having to explicitly control the hooks (see #364 and #368).

You need to modify the `hooks.lua` module to get the following behaviour.

1. Create `foo.lua` module that will **extend** the explicit `before_all/after_all` hooks:
```lua
local hooks = require('luatest.hooks')
local m

function m.init()
    print('[m] init')
end

function m.clean()
    print('[m] clean')
end

hooks.before_all_custom(m.init) <-- new public-function from hooks.lua
hooks.after_all_custom(m.clean)

return haha
```

2. I expect to see that this logic has been run as a default `before/after` hooks:
```text
> [bar] before_suite
[m] init                   <-- new custom hook here
> [bar] before_all
    bar.test_a ... 
> > [bar] before_each
> > > [bar] before_test_a
> > > [bar] after_test_a
> > [bar] after_each
    bar.test_a ... (0.000s) Ok
    bar.test_b ... 
> > [bar] before_each
> > > [bar] before_test_b
> > > [bar] after_test_b
> > [bar] after_each
    bar.test_b ... (0.000s) Ok
[m] clean                 <-- new custom hook here
> [bar] after_all
> [bar] after_suite
```

**Comment by Totktonada** [comment]
My two coins.

Let's assume that two modules set default hooks.

```lua
-- x.lua
hooks.before_all_custom(function() print('[x] init') end)
hooks.after_all_custom(function() print('[x] clean') end)
```

```lua
-- y.lua
hooks.before_all_custom(function() print('[y] init') end)
hooks.after_all_custom(function() print('[y] clean') end)
```

I expect the following order of the hooks execution (if `x` is `require`d first):

```lua
<...>
[x] init
[y] init
<...>
[y] clean -- reverse order!
[x] clean
<...>
```

or the following (if `y` is first):


```lua
<...>
[y] init
[x] init
<...>
[x] clean -- reverse order!
[y] clean
<...>
```

But not the following.

```lua
<...>
[x] init
[y] init
<...>
[x] clean -- direct order -- NO!
[y] clean
<...>
```

It allows dependent modules set the hooks and perform the cleanup from the upper level to the lower one. Same as in `treegen` and `cluster`. We should stop clusters and then drop their files.

----

Also, I think that 'custom' is not the best term here. In fact, 'custom' has very vague meaning and means almost nothing. IMHO, it is often a kind of a placeholder word.

I'm thinking about these hooks as default before_all, default after_all and so on. The 'default' word means that when a test file executed, these pre-registered hooks are added by default.

BTW, `preloaded', `pre-registered` are suitable terms here.

We can also name them 'auto hooks', because they're added automatically.

Or 'external hooks' to highlight that they arrive from outside of the test. (This variant is dubious, because a usual before_all hook may have its code `require`d from outside of the test.)

There are many variants that look more suitable than 'custom'.

**Comment by ochaplashkin** [comment]
@Totktonada 
I agree. This is the main reason I've been working on this for so long.

I expected to see default "wrappers" like `a - b - c - c - b - a`, but the order of the `after` hooks should be changed.

Yesterday I tested the new behaviour and the order is now: `a - b - c - a - b - c`

**Q:** Should we fix the sequence of hooks in this PR or leave it for later?

**Comment by Totktonada** [comment]
I see no conceptual problems in reversing the order of the `after_*` hooks. I'd implement it from scratch to avoid compatibility problems at the point of the order change in the future.

**Comment by Totktonada** [comment]
I would like to make my statement above more clear after a f2f discussion with Oleg.

Say, we have a test:

```lua
local t = require('luatest')

local g = t.group()

g.before_all(function() print('test::before_all::foo') end)
g.after_all(function() print('test::after_all::foo') end)

g.before_all(function() print('test::before_all::bar') end)
g.after_all(function() print('test::after_all::bar') end)
```

The hooks that are defined in a test are executed in the order of registration: as for `before_*` as well as for `after_*` hooks:

```lua
test::before_all::foo
test::before_all::bar
<..test cases..>
test::after_all::foo
test::after_all::bar
```

This order is not very intuitive, but existing tests lean on it. We can't change it.

It is not a large problem, in fact, because the test can be adjusted:

```lua

g.before_all(function() print('test::before_all::foo') end)
g.before_all(function() print('test::before_all::bar') end)

g.after_all(function() print('test::after_all::bar') end)
g.after_all(function() print('test::after_all::foo') end)
```

It gives the needed order:

```lua
test::before_all::foo
test::before_all::bar
<..test cases..>
test::after_all::bar
test::after_all::foo
```

The things are different with modules that define default hooks: we can't define all the before-hooks first and all the after-hooks then. Once we require a module all its before- and after-hooks are registered.

It means that we should register the after hooks in the reverse order **for the default hooks** (ones that are named custom/auto/preloaded above). This functionality doesn't exist now, so it doesn't break any compatibility.

But, again, existing usual before/after-hooks registered from a test using a test group **should keep existing execution order**. I'm not very happy about this behavior, but the compatibility is more important.
